---
- hosts: devices
  connection: local

  tasks:
       - include_vars: ../vars.yml

       - name: Get Running Configuration
         ios_command:
                 commands:
                         - show running-config
         register: config

       - name: Create directory to save show output
         file:
                 path: "{{ base_path }}/RUNNING"
                 state: directory
                 owner: mihai
                 group: mihai
                 mode: 0775
                 recurse: yes


       - name: save output to local directory
         copy:
           content: "{{ config.stdout | replace('\\n', '\n') }}"
           dest: "{{ base_path }}/RUNNING/{{ inventory_hostname }}.ios"
